### PR TITLE
fix: warn the glob option "as" has been deprecated in favour of "query"

### PR DESCRIPTION
**Pull request by TatoRamirez**
Update as: 'raw' to query: '?raw', import: 'default'

### CODE REVIEW

**Comment by wokalek** [comment]
@gitFoxCode 
This will actually remove the annoying warnings, please take a look at this pull request!

image

**Comment by MoeinMirkiani** [comment]
having the same issue :(

**Comment by AndreasMueck** [comment]
A temporary fix is to edit the component nuxt-icons directly:

/node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue

21: change `as: 'raw'` to `query: 'raw'`

**Comment by nossienl** [comment]
@gitFoxCode can you please merge this ?

**Comment by CarlosGranadosM** [comment]
@gitFoxCode :)

**Pull request merged**
